version: '1'
services:
  db: 
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=tatuajes
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5555:5432"

  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"